# longtou.2024
FROM gcr.io/deeplearning-platform-release/pytorch-cu121.2-3.py310

RUN apt update && apt install -y file # webdataset cache_dir error
WORKDIR /root
COPY lite/CosyVoice /root/CosyVoice
WORKDIR /root/CosyVoice
RUN ./setup_miniforge.sh conda cosyvoice 3.10
RUN  . ./activate_python.sh  && pip install -r requirements.txt
COPY CosyVoice /root/CosyVoice
# for qwen3
RUN . ./activate_python.sh && pip install transformers==4.55.4
WORKDIR /root/CosyVoice/examples/aihub/cosyvoice2

CMD ["/bin/bash"]
