apiVersion: v1
kind: PersistentVolume
metadata:
  name: longtou-gcs-fuse-csi-pv3
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Pi
  storageClassName: longtou-example-storage-class
  claimRef:
    namespace: kubeflow
    name: longtou-gcs-fuse-csi-static-pvc3
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: prod-ai-lab-speech-bucket
    volumeAttributes:
      gcsfuseLoggingSeverity: warning
      fileCacheCapacity: "-1"
