apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longtou-gcs-fuse-csi-static-pvc3
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
  volumeName: longtou-gcs-fuse-csi-pv3
  storageClassName: longtou-example-storage-class
